EquipParamGemPreprocessedTable = {
    ["Field 1"] = "u8 disableParam_NT:1",
    ["Field 2"] = "h8 disableParamReserve1:7",
    ["Field 3"] = "h16 disableParamReserve2[3]",
    ["Field 4"] = "u16 iconId",
    ["Field 5"] = "s8 rank",
    ["Field 6"] = "u8 sortGroupId = 255",
    ["Field 7"] = "s32 spEffectId0 = -1",
    ["Field 8"] = "s32 spEffectId1 = -1",
    ["Field 9"] = "s32 spEffectId2 = -1",
    ["Field 10"] = "u32 itemGetTutorialFlagId",
    ["Field 11"] = "s32 swordArtsParamId = -1",
    ["Field 12"] = "s32 mountValue",
    ["Field 13"] = "s32 sellValue",
    ["Field 14"] = "s32 saleValue = -1",
    ["Field 15"] = "s32 sortId",
    ["Field 16"] = "s16 compTrophySedId = -1",
    ["Field 17"] = "s16 trophySeqId = -1",
    ["Field 18"] = "u8 configurableWepAttr00:1",
    ["Field 19"] = "u8 configurableWepAttr01:1",
    ["Field 20"] = "u8 configurableWepAttr02:1",
    ["Field 21"] = "u8 configurableWepAttr03:1",
    ["Field 22"] = "u8 configurableWepAttr04:1",
    ["Field 23"] = "u8 configurableWepAttr05:1",
    ["Field 24"] = "u8 configurableWepAttr06:1",
    ["Field 25"] = "u8 configurableWepAttr07:1",
    ["Field 26"] = "u8 configurableWepAttr08:1",
    ["Field 27"] = "u8 configurableWepAttr09:1",
    ["Field 28"] = "u8 configurableWepAttr10:1",
    ["Field 29"] = "u8 configurableWepAttr11:1",
    ["Field 30"] = "u8 configurableWepAttr12:1",
    ["Field 31"] = "u8 configurableWepAttr13:1",
    ["Field 32"] = "u8 configurableWepAttr14:1",
    ["Field 33"] = "u8 configurableWepAttr15:1",
    ["Field 34"] = "u8 rarity",
    ["Field 35"] = "u8 configurableWepAttr16:1",
    ["Field 36"] = "u8 configurableWepAttr17:1",
    ["Field 37"] = "u8 configurableWepAttr18:1",
    ["Field 38"] = "u8 configurableWepAttr19:1",
    ["Field 39"] = "u8 configurableWepAttr20:1",
    ["Field 40"] = "u8 configurableWepAttr21:1",
    ["Field 41"] = "u8 configurableWepAttr22:1",
    ["Field 42"] = "u8 configurableWepAttr23:1",
    ["Field 43"] = "u8 isDiscard:1",
    ["Field 44"] = "u8 isDrop:1",
    ["Field 45"] = "u8 isDeposit:1",
    ["Field 46"] = "u8 disableMultiDropShare:1",
    ["Field 47"] = "u8 showDialogCondType:2 = 2",
    ["Field 48"] = "u8 showLogCondType:1 = 1",
    ["Field 49"] = "u8 pad:1", -- u8 but should be h1
    ["Field 50"] = "u8 defaultWepAttr",
    ["Field 51"] = "h16 pad2[2]",
    ["Field 52"] = "u8 canMountWep_Dagger:1",
    ["Field 53"] = "u8 canMountWep_SwordNormal:1",
    ["Field 54"] = "u8 canMountWep_SwordLarge:1",
    ["Field 55"] = "u8 canMountWep_SwordGigantic:1",
    ["Field 56"] = "u8 canMountWep_SaberNormal:1",
    ["Field 57"] = "u8 canMountWep_SaberLarge:1",
    ["Field 58"] = "u8 canMountWep_katana:1",
    ["Field 59"] = "u8 canMountWep_SwordDoubleEdge:1",
    ["Field 60"] = "u8 canMountWep_SwordPierce:1",
    ["Field 61"] = "u8 canMountWep_RapierHeavy:1",
    ["Field 62"] = "u8 canMountWep_AxeNormal:1",
    ["Field 63"] = "u8 canMountWep_AxeLarge:1",
    ["Field 64"] = "u8 canMountWep_HammerNormal:1",
    ["Field 65"] = "u8 canMountWep_HammerLarge:1",
    ["Field 66"] = "u8 canMountWep_Flail:1",
    ["Field 67"] = "u8 canMountWep_SpearNormal:1",
    ["Field 68"] = "u8 canMountWep_SpearLarge:1",
    ["Field 69"] = "u8 canMountWep_SpearHeavy:1",
    ["Field 70"] = "u8 canMountWep_SpearAxe:1",
    ["Field 71"] = "u8 canMountWep_Sickle:1",
    ["Field 72"] = "u8 canMountWep_Knuckle:1",
    ["Field 73"] = "u8 canMountWep_Claw:1",
    ["Field 74"] = "u8 canMountWep_Whip:1",
    ["Field 75"] = "u8 canMountWep_AxhammerLarge:1",
    ["Field 76"] = "u8 canMountWep_BowSmall:1",
    ["Field 77"] = "u8 canMountWep_BowNormal:1",
    ["Field 78"] = "u8 canMountWep_BowLarge:1",
    ["Field 79"] = "u8 canMountWep_ClossBow:1",
    ["Field 80"] = "u8 canMountWep_Ballista:1",
    ["Field 81"] = "u8 canMountWep_Staff:1",
    ["Field 82"] = "u8 canMountWep_Sorcery:1",
    ["Field 83"] = "u8 canMountWep_Talisman:1",
    ["Field 84"] = "u8 canMountWep_ShieldSmall:1",
    ["Field 85"] = "u8 canMountWep_ShieldNormal:1",
    ["Field 86"] = "u8 canMountWep_ShieldLarge:1",
    ["Field 87"] = "u8 canMountWep_Torch:1",
    ["Field 88"] = "u8 reserved_canMountWep:4",
    ["Field 89"] = "h24 reserved2_canMountWep[3]",
    ["Field 90"] = "s32 spEffectMsgId0 = -1",
    ["Field 91"] = "s32 spEffectMsgId1 = -1",
    ["Field 92"] = "s32 spEffectId_forAtk0 = -1",
    ["Field 93"] = "s32 spEffectId_forAtk1 = -1",
    ["Field 94"] = "s32 spEffectId_forAtk2 = -1",
    ["Field 95"] = "s32 mountWepTextId = -1",
    ["Field 96"] = "h64 pad6[8]"

}